fix(ci): azurerm unsupported module validation
Modules should never specify their own providers per
https://www.terraform.io/docs/language/modules/develop/providers.html

But for azurerm resources, the `terraform validate` says:

  Error: "features": required field is not set

So it looks for `provider azurerm { features {} }` which it does not
find within a module.

The modules need to be validated through examples unfortunately for now.